from django.urls import path

from . import views

app_name = "sales"

urlpatterns = [
    path("nueva/", views.nueva_venta, name="nueva_venta"),
    path("pendientes/", views.venta_pendientes_buscar, name="venta_pendientes_buscar"),
    path("pendientes/<int:venta_id>/", views.venta_completar, name="venta_completar"),
    path("pendientes/<int:venta_id>/notificado/", views.marcar_notificado, name="marcar_notificado"),
    path("pendientes/<int:venta_id>/entregado/", views.marcar_entregado, name="marcar_entregado"),
    path("obra-social/", views.venta_obra_social_lista, name="venta_obra_social_lista"),
    path("obra-social/<int:venta_id>/resuelta/", views.marcar_obra_social_resuelta, name="marcar_obra_social_resuelta"),
    path("<int:venta_id>/", views.pos, name="pos"),
    path("<int:venta_id>/detalle/", views.venta_detalle, name="venta_detalle"),
    path("<int:venta_id>/eliminar/", views.venta_eliminar, name="venta_eliminar"),
    path("<int:venta_id>/cancelar/", views.cancelar_venta, name="cancelar_venta"),
    path("<int:venta_id>/clientes/buscar/", views.buscar_clientes, name="buscar_clientes"),
    path("<int:venta_id>/cliente/", views.set_cliente, name="set_cliente"),
    path("<int:venta_id>/cliente/nuevo-rapido/", views.cliente_nuevo_rapido, name="cliente_nuevo_rapido"),
    path("<int:venta_id>/cliente/email-rapido/", views.cliente_email_rapido, name="cliente_email_rapido"),
    path("<int:venta_id>/cliente/editar-rapido/", views.cliente_editar_rapido, name="cliente_editar_rapido"),
    path("<int:venta_id>/receta-venta/", views.asociar_receta_venta, name="asociar_receta_venta"),
    path("<int:venta_id>/receta-nueva-modal/", views.receta_modal_form, name="receta_modal_form"),
    path("<int:venta_id>/receta-nueva-modal/crear/", views.receta_modal_crear, name="receta_modal_crear"),
    path("recetas/<int:receta_id>/detalle/", views.detalle_receta, name="detalle_receta"),
    path("<int:venta_id>/vendedor/", views.set_vendedor, name="set_vendedor"),
    path("<int:venta_id>/forma-pago/", views.set_forma_pago, name="set_forma_pago"),
    path("<int:venta_id>/obra-social/", views.set_obra_social, name="set_obra_social"),
    path("<int:venta_id>/obra-social/cual/", views.set_obra_social_cual, name="set_obra_social_cual"),
    path("<int:venta_id>/descuento-manual/", views.aplicar_descuento_manual, name="aplicar_descuento_manual"),
    path("<int:venta_id>/observaciones/", views.set_observaciones, name="set_observaciones"),
    path("<int:venta_id>/recetas/", views.recetas_de_cliente, name="recetas_de_cliente"),
    path("<int:venta_id>/recetas/buscar/", views.buscar_recetas, name="buscar_recetas"),
    path("<int:venta_id>/armazones/", views.armazones_de_venta, name="armazones_de_venta"),
    path("<int:venta_id>/catalogo/buscar/", views.buscar_catalogo, name="buscar_catalogo"),
    path("<int:venta_id>/catalogo/agregar/", views.agregar_item_catalogo, name="agregar_item_catalogo"),
    path("<int:venta_id>/express/agregar/", views.agregar_item_express, name="agregar_item_express"),
    path("<int:venta_id>/escanear/consultar/", views.consultar_codigo, name="consultar_codigo"),
    path("<int:venta_id>/escanear/", views.escanear, name="escanear"),
    path("<int:venta_id>/items/<int:item_id>/quitar/", views.quitar_item, name="quitar_item"),
    path("<int:venta_id>/items/<int:item_id>/precio/", views.set_precio_item, name="set_precio_item"),
    path("<int:venta_id>/items/<int:item_id>/receta/", views.asociar_receta, name="asociar_receta"),
    path("<int:venta_id>/items/<int:item_id>/orden-laboratorio/", views.generar_orden_laboratorio, name="generar_orden_laboratorio"),
    path("<int:venta_id>/items/<int:item_id>/promocion/", views.asociar_promocion_item, name="asociar_promocion_item"),
    path("<int:venta_id>/items/<int:item_id>/entregado/", views.set_item_entregado, name="set_item_entregado"),
    path("<int:venta_id>/items/<int:item_id>/armazon/", views.asociar_armazon_item, name="asociar_armazon_item"),
    path("<int:venta_id>/confirmar/", views.confirmar_venta, name="confirmar_venta"),
    path("<int:venta_id>/ticket/", views.venta_ticket, name="venta_ticket"),

    path("vendedores/", views.VendedorListView.as_view(), name="vendedor_lista"),
    path("vendedores/nuevo/", views.VendedorCreateView.as_view(), name="vendedor_nuevo"),
    path("vendedores/<int:pk>/editar/", views.VendedorUpdateView.as_view(), name="vendedor_editar"),
    path("vendedores/<int:pk>/eliminar/", views.VendedorDeleteView.as_view(), name="vendedor_eliminar"),

    path("devoluciones/", views.DevolucionListView.as_view(), name="devolucion_lista"),
    path("devoluciones/nueva/", views.devolucion_nueva, name="devolucion_nueva"),
    path("devoluciones/registrar/", views.devolucion_registrar, name="devolucion_registrar"),

    path("caja/", views.caja_del_dia, name="caja_del_dia"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("historial/", views.VentaListView.as_view(), name="venta_lista"),
]
