# Generated by Django 6.0.6 on 2026-07-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('sales', '0018_vendedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionpush',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Quién usa este dispositivo (se elige al activar los avisos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones_push', to='sales.vendedor'),
        ),
    ]
