# Generated by Django 6.0.6 on 2026-08-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Óptica', help_text='Aparece en el ticket, las órdenes de laboratorio y los avisos.', max_length=120, verbose_name='Nombre de la óptica')),
                ('nombre_corto', models.CharField(blank=True, help_text='El que se ve debajo del ícono en el celular. Si se deja vacío, se usa el nombre.', max_length=30, verbose_name='Nombre corto')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=60, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('logo', models.ImageField(blank=True, help_text='Se muestra en la barra superior y en las impresiones. Ideal cuadrado, fondo transparente.', upload_to='marca/', verbose_name='Logo')),
                ('color_primario', models.CharField(default='#0d6efd', help_text='Color de marca en formato #rrggbb. Se usa en botones, links y destacados.', max_length=7, verbose_name='Color principal')),
                ('mensaje_ticket', models.CharField(blank=True, default='¡Gracias por su compra!', max_length=120, verbose_name='Mensaje al pie del ticket')),
                ('caracteristica_telefonica', models.CharField(blank=True, help_text='Sin 0 ni 15 (ej: 3489). Si se completa, los teléfonos que se carguen con solo el número local se completan solos con esta característica. Vacío = no tocar los teléfonos.', max_length=5, verbose_name='Característica de la zona')),
                ('largo_telefono_local', models.PositiveSmallIntegerField(default=6, help_text='Cuántos dígitos tiene un número de la zona sin la característica.', verbose_name='Dígitos del número local')),
                ('codigo_pais', models.CharField(default='54', help_text='Sin el +. Se usa para armar los links de WhatsApp.', max_length=5, verbose_name='Código de país')),
                ('prefijo_movil', models.CharField(blank=True, default='9', help_text='Va entre el código de país y el número (en Argentina, 9). Vacío si tu país no lo usa.', max_length=5, verbose_name='Prefijo de celular')),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuración',
            },
        ),
    ]
