# Generated by Django 6.0.6 on 2026-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='logo',
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='color_primario',
            field=models.CharField(default='#a8563a', help_text='Color de marca en formato #rrggbb. Se usa en botones, links y destacados.', max_length=7, verbose_name='Color principal'),
        ),
    ]
