# Generated by Django 6.0.6 on 2026-09-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
