# Generated by Django 6.0.6 on 2026-07-03 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('requiere_receta', models.BooleanField(default=False, help_text='Marcar para cristales / lentes de contacto: se podrán asociar a una receta al venderse.')),
            ],
            options={
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(db_index=True, help_text='Código interno propio, el que se imprime en la etiqueta.', max_length=64, unique=True)),
                ('codigo_patilla', models.CharField(blank=True, help_text='Código opcional del fabricante/proveedor (el que suele venir impreso en la patilla del armazón).', max_length=64)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('color_cristal', models.CharField(blank=True, max_length=60)),
                ('calibre', models.CharField(blank=True, help_text="Ancho del aro, ej: '52'", max_length=30)),
                ('material', models.CharField(blank=True, help_text='Ej: Acetato, Metal, TR90', max_length=60)),
                ('talle', models.CharField(blank=True, max_length=30)),
                ('grupo', models.CharField(blank=True, help_text='Agrupador libre para reportes/filtros', max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('U', 'Unisex')], max_length=1)),
                ('rango_edad', models.CharField(blank=True, choices=[('NIN', 'Niños'), ('JUV', 'Juvenil'), ('OTR', 'Otro')], max_length=3)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, help_text='Costo sin IVA', max_digits=10)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta, con IVA incluido', max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0, help_text='Para alertas de reposición (fase futura)')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('ADJ', 'Ajuste')], max_length=3)),
                ('cantidad', models.IntegerField(help_text='Positivo siempre; en Ajuste puede representar resta si se usa negativo.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
