# Generated by Django 5.2.15 on 2026-07-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='controla_stock',
            field=models.BooleanField(default=True, help_text='Desmarcar para categorías que no son stock físico (ej: cristales hechos a medida en laboratorio). Esos productos no se escanean ni descuentan stock: se eligen de una lista al vender y solo suman su precio.'),
        ),
    ]
