# Generated by Django 5.2.15 on 2026-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_categoria_controla_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Costo sin IVA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(blank=True, default=0, help_text='Para alertas de reposición (fase futura)'),
        ),
    ]
