# Generated by Django 5.2.15 on 2026-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_descuento', models.CharField(choices=[('PCT', 'Porcentaje'), ('FIJ', 'Monto fijo')], default='PCT', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si es porcentaje: un número de 0 a 100 (ej 15). Si es monto fijo: el descuento en $.', max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío si no tiene fecha de fin definida.', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('marcas', models.CharField(blank=True, help_text='Marcas separadas por coma (ej: Ray-Ban, Oakley). Vacío = no filtra por marca.', max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='promociones', to='inventory.categoria')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='inventory.producto')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
