# Generated by Django 5.2.15 on 2026-07-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Código interno propio, el que se imprime en la etiqueta. Se genera solo si se deja vacío.', max_length=64, unique=True),
        ),
    ]
