# Generated by Django 5.2.15 on 2026-07-05 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_producto_cleanup_campos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscaneoNoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=64)),
                ('origen', models.CharField(choices=[('VTA', 'Punto de venta'), ('ING', 'Ingreso rápido de stock')], default='VTA', max_length=3)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False, help_text='Marcar cuando ya se revisó/resolvió (ej: se cargó el producto).')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos_no_encontrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'escaneos no encontrados',
                'ordering': ['-fecha'],
            },
        ),
    ]
