# Generated by Django 5.2.15 on 2026-07-05 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_escaneonoencontrado'),
        ('sales', '0007_venta_incidencias_detalle_venta_tiene_incidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaneonoencontrado',
            name='venta',
            field=models.ForeignKey(blank=True, help_text='Si el escaneo ocurrió durante una venta, referencia a esa venta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos_no_encontrados', to='sales.venta'),
        ),
    ]
