# Generated by Django 5.2.15 on 2026-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_escaneonoencontrado_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='tipo_descuento',
            field=models.CharField(choices=[('PCT', 'Porcentaje'), ('FIJ', 'Monto fijo'), ('2X1', '2x1 (cada 2 unidades, 1 es gratis)')], default='PCT', max_length=3),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Si es porcentaje: un número de 0 a 100 (ej 15). Si es monto fijo: el descuento en $. Si es 2x1, no se usa (dejar en 0).', max_digits=10),
        ),
    ]
