# Generated by Django 5.2.15 on 2026-07-09 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_marca_modelo_obligatorios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('ENV', 'Enviada'), ('PAR', 'Recibida parcialmente'), ('REC', 'Recibida'), ('CAN', 'Cancelada')], default='BOR', max_length=3)),
                ('notas', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='inventory.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'órdenes de compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_texto', models.CharField(blank=True, help_text='Solo para ítems nuevos, que no están en el catálogo.', max_length=80)),
                ('modelo_texto', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(blank=True, help_text='Color, calibre u otro detalle.', max_length=255)),
                ('cantidad_pedida', models.PositiveIntegerField(default=1)),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.ordencompra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_orden_compra', to='inventory.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
