# Generated by Django 6.0.6 on 2026-07-10 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_ordencompra_ordencompraitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanFinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: '6 cuotas sin interés', 'Ahora 12'", max_length=120)),
                ('cuotas', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_financiero_pct', models.DecimalField(decimal_places=2, help_text='% que se descuenta del precio de venta si el comercio absorbe el costo de la promo (no se lo traslada al cliente). Ej: 12.5', max_digits=5)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, help_text='Dejar vacío si no tiene fecha de fin definida.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='inventory.banco')),
            ],
            options={
                'ordering': ['banco__nombre', 'cuotas'],
            },
        ),
    ]
