# Generated by Django 6.0.6 on 2026-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_seed_bancos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfinanciacion',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='planes_financiacion', to='inventory.categoria'),
        ),
        migrations.AddField(
            model_name='planfinanciacion',
            name='marcas',
            field=models.CharField(blank=True, help_text='Marcas separadas por coma (ej: Ray-Ban, Oakley). Vacío = no filtra por marca.', max_length=500),
        ),
        migrations.AddField(
            model_name='planfinanciacion',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='planes_financiacion', to='inventory.proveedor'),
        ),
    ]
