# Generated by Django 6.0.6 on 2026-07-21 01:56

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_merge_duplicate_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='categoria_nombre_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='marca_nombre_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='proveedor_nombre_ci_unique'),
        ),
    ]
