# Generated by Django 6.0.6 on 2026-07-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_categoria_nombre_alter_marca_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='requiere_receta',
            field=models.BooleanField(default=False, help_text='Marcar para cristales / lentes de contacto: al venderse se les puede asociar una receta (opcional, puede ser una venta sin aumento). Los armazones NO: son solo el armazón.', verbose_name='trabaja con recetas'),
        ),
    ]
