# Generated by Django 6.0.6 on 2026-07-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_corregir_categorias_receta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'orden de compra', 'verbose_name_plural': 'órdenes de compra'},
        ),
    ]
