# Generated by Django 6.0.6 on 2026-07-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_rename_requiere_receta_categoria_usa_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
