# Generated by Django 6.0.6 on 2026-09-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_producto_eliminado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
    ]
