# Generated by Django 6.0.6 on 2026-07-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_nombre_apellido_obligatorios'),
        ('sales', '0014_ventaitem_armazon_de_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaLentesContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suelto', models.CharField(blank=True, help_text='Nombre de quien se prueba, si todavía no está cargado como cliente.', max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('fecha_hora', models.DateTimeField(help_text='Cuándo está agendada la prueba.')),
                ('estado', models.CharField(choices=[('AGE', 'Agendada'), ('REA', 'Realizada'), ('CAN', 'Cancelada')], default='AGE', max_length=3)),
                ('hubo_venta', models.BooleanField(default=False)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Cuánto pagó el cliente, si la prueba terminó en venta.', max_digits=10, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_lentes_contacto', to='customers.cliente')),
                ('vendedor', models.ForeignKey(help_text='Quién hace la prueba.', on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_lentes_contacto', to='sales.vendedor')),
            ],
            options={
                'verbose_name': 'prueba de lentes de contacto',
                'verbose_name_plural': 'pruebas de lentes de contacto',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
