# Generated by Django 6.0.6 on 2026-07-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_lenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebalentescontacto',
            name='estado',
            field=models.CharField(choices=[('AGE', 'Agendada'), ('REA', 'Realizada'), ('COB', 'Cobrada por Guille'), ('CAN', 'Cancelada')], default='AGE', max_length=3),
        ),
    ]
