# Generated by Django 6.0.6 on 2026-07-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_lenses', '0002_alter_pruebalentescontacto_estado'),
        ('sales', '0014_ventaitem_armazon_de_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebalentescontacto',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='pruebalentescontacto',
            name='hubo_venta',
        ),
        migrations.RemoveField(
            model_name='pruebalentescontacto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='pruebalentescontacto',
            name='venta',
            field=models.ForeignKey(blank=True, help_text='Venta que generó esta prueba (si terminó en venta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prueba_lentes', to='sales.venta'),
        ),
    ]
