# Generated by Django 6.0.6 on 2026-07-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_lenses', '0003_remove_pruebalentescontacto_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebalentescontacto',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, help_text='Ya se envió el aviso recordatorio del día de la prueba.'),
        ),
    ]
