# Generated by Django 6.0.6 on 2026-07-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_lenses', '0004_pruebalentescontacto_recordatorio_enviado'),
        ('prescriptions', '0009_receta_es_lentes_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebalentescontacto',
            name='receta',
            field=models.ForeignKey(blank=True, help_text='Graduación del cliente asociada a esta prueba.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_lentes_contacto', to='prescriptions.receta'),
        ),
    ]
