# Generated by Django 6.0.6 on 2026-07-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_lenses', '0005_pruebalentescontacto_receta'),
        ('customers', '0006_sembrar_obras_sociales'),
        ('prescriptions', '0009_receta_es_lentes_contacto_and_more'),
        ('sales', '0018_vendedor_usuario'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pruebalentescontacto',
            index=models.Index(fields=['estado', 'fecha_hora'], name='prueba_estado_fecha_idx'),
        ),
    ]
