# Generated by Django 6.0.6 on 2026-07-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=120)),
                ('doctor', models.CharField(blank=True, help_text='Oftalmólogo/a que la emitió', max_length=150)),
                ('obra_social', models.CharField(blank=True, max_length=120)),
                ('lejos_od_esfera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_od_cilindro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_od_eje', models.IntegerField(blank=True, null=True)),
                ('lejos_od_adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_oi_esfera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_oi_cilindro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_oi_eje', models.IntegerField(blank=True, null=True)),
                ('lejos_oi_adicion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_dnp', models.CharField(blank=True, help_text="Ej: '31/31.5'", max_length=30)),
                ('lejos_tipo_cristal', models.CharField(blank=True, max_length=60)),
                ('lejos_color_cristal', models.CharField(blank=True, max_length=60)),
                ('lejos_tratamientos', models.CharField(blank=True, help_text='Ej: antirreflejo, filtro azul', max_length=150)),
                ('cerca_od_esfera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_od_cilindro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_od_eje', models.IntegerField(blank=True, null=True)),
                ('cerca_oi_esfera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_oi_cilindro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_oi_eje', models.IntegerField(blank=True, null=True)),
                ('cerca_dnp', models.CharField(blank=True, max_length=30)),
                ('cerca_tipo_cristal', models.CharField(blank=True, max_length=60)),
                ('cerca_color_cristal', models.CharField(blank=True, max_length=60)),
                ('cerca_tratamientos', models.CharField(blank=True, max_length=150)),
                ('es_bifocal_multifocal', models.CharField(blank=True, help_text='Tipo, si aplica', max_length=60)),
                ('di_lejos', models.CharField(blank=True, max_length=30)),
                ('di_cerca', models.CharField(blank=True, max_length=30)),
                ('altura', models.CharField(blank=True, max_length=30)),
                ('tipo_sobre', models.CharField(choices=[('TAL', 'Sobre de taller'), ('PRE', 'Presupuesto'), ('NOI', 'No imprimir'), ('DEV', 'Devolución')], default='TAL', max_length=3)),
                ('forma_pago', models.CharField(blank=True, max_length=60)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, help_text='Foto/escaneo de la receta original', null=True, upload_to='recetas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('armazon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_con_este_armazon', to='inventory.producto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='customers.cliente')),
            ],
            options={
                'verbose_name_plural': 'recetas',
                'ordering': ['-fecha_recibido'],
            },
        ),
    ]
