# Generated by Django 5.2.15 on 2026-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='entregada',
            field=models.BooleanField(default=False, help_text='Marcar cuando el cliente retira el pedido terminado.'),
        ),
    ]
