# Generated by Django 5.2.15 on 2026-07-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_receta_entregada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='vendedor',
        ),
    ]
