# Generated by Django 5.2.15 on 2026-07-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_receta_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='anticipo',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='armazon',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='descuento_pct',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='tipo_sobre',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='total',
        ),
    ]
