# Generated by Django 5.2.15 on 2026-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_remove_receta_anticipo_remove_receta_armazon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='correcciones',
            field=models.JSONField(blank=True, default=dict, help_text='Valor anterior de cada campo que se corrigió, para mostrarlo tachado junto al nuevo.'),
        ),
    ]
