# Generated by Django 5.2.15 on 2026-07-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_nombre_apellido_obligatorios'),
        ('inventory', '0015_ordencompra_ordencompraitem'),
        ('prescriptions', '0005_receta_correcciones'),
        ('sales', '0009_venta_cuotas_saldo_venta_descuento_manual_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de enviar'), ('ENV', 'Enviada al laboratorio'), ('REC', 'Recibida')], default='PEN', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_laboratorio', to='customers.cliente')),
                ('producto', models.ForeignKey(help_text='Armazón elegido para esta orden.', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_laboratorio', to='inventory.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_laboratorio', to='prescriptions.receta')),
                ('venta_item', models.ForeignKey(blank=True, help_text='Ítem de venta que generó esta orden (si vino del punto de venta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_laboratorio', to='sales.ventaitem')),
            ],
            options={
                'verbose_name_plural': 'órdenes de laboratorio',
                'ordering': ['-creado'],
            },
        ),
    ]
