# Generated by Django 5.2.15 on 2026-07-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_ordencompra_ordencompraitem'),
        ('prescriptions', '0006_ordenlaboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='armazon',
            field=models.ForeignKey(blank=True, help_text='Armazón donde se monta el cristal, si también se vendió en la misma venta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.producto'),
        ),
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='armazon_de_cliente',
            field=models.BooleanField(default=False, help_text='El cliente trajo su propio armazón.'),
        ),
        migrations.AlterField(
            model_name='ordenlaboratorio',
            name='producto',
            field=models.ForeignKey(help_text='Producto que generó la orden (el cristal, si es el que lleva la receta asociada).', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_laboratorio', to='inventory.producto'),
        ),
    ]
