# Generated by Django 6.0.6 on 2026-07-21 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_ordenlaboratorio_armazon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cargada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que cargó la receta en el sistema (para el historial de carga de recetas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_cargadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
