# Generated by Django 6.0.6 on 2026-07-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_receta_cargada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='es_lentes_contacto',
            field=models.BooleanField(default=False, help_text='La receta es para lentes de contacto.'),
        ),
        migrations.AddField(
            model_name='receta',
            name='marca_lentes_contacto',
            field=models.CharField(blank=True, help_text='Marca de los lentes de contacto (si es para lentes de contacto).', max_length=80),
        ),
    ]
