# Generated by Django 6.0.6 on 2026-07-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_receta_es_lentes_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
