# Generated by Django 6.0.6 on 2026-07-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_receta_eliminado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='medico',
            field=models.ForeignKey(blank=True, help_text='Oftalmólogo/a que la emitió', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='prescriptions.medico'),
        ),
    ]
