# Generated by Django 6.0.6 on 2026-07-27 12:26

from django.db import migrations


def backfill(apps, schema_editor):
    """Crea un Medico por cada valor distinto (case/espacios-insensitive) que
    haya en Receta.doctor, y apunta cada receta al Medico correspondiente.

    LIMITACIÓN CONOCIDA: solo dedupea variantes idénticas salvo mayúsculas y
    espacios extra. Variantes con el nombre en otro orden (ej. "Fernando
    Loza" vs "Loza Fernando") NO se fusionan automáticamente acá y quedan
    como registros de Medico separados — se pueden unificar a mano después
    reasignando las recetas correspondientes desde el admin.
    """
    db_alias = schema_editor.connection.alias
    Medico = apps.get_model("prescriptions", "Medico")
    Receta = apps.get_model("prescriptions", "Receta")
    por_clave = {}
    for receta in Receta.objects.using(db_alias).exclude(doctor="").iterator():
        nombre = " ".join(receta.doctor.split())
        if not nombre:
            continue
        clave = nombre.lower()
        medico = por_clave.get(clave)
        if medico is None:
            medico = Medico.objects.using(db_alias).create(nombre=nombre)
            por_clave[clave] = medico
        receta.medico_id = medico.id
        receta.save(update_fields=["medico_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_medico_receta_medico'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
