# Generated by Django 6.0.6 on 2026-07-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0012_backfill_medico_from_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='doctor',
        ),
    ]
