# Generated by Django 6.0.6 on 2026-07-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_obrasocial_nombre_and_more'),
        ('prescriptions', '0013_remove_receta_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='obra_social_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='customers.obrasocial'),
        ),
    ]
