# Generated by Django 6.0.6 on 2026-07-27

from django.db import migrations

# Mapeo a mano: la obra social de la receta era texto libre y acumuló
# mayúsculas sueltas y typos ("paticular", "s medicaL", etc.) que un simple
# case-insensitive no arregla. Nombres que ya existen en el catálogo
# customers.ObraSocial se reusan tal cual; el resto se crea como entrada
# nueva (revisado a mano contra la producción real). La clave del dict ya
# está en minúscula porque se compara contra el valor normalizado.
MAPEO = {
    "particular": "Particular",
    "paticular": "Particular",
    "patrticular": "Particular",
    "perticular": "Particular",
    "osde": "OSDE",
    "osde 210": "OSDE 210",
    "osde 310": "OSDE 310",
    "osde 410": "OSDE 410",
    "ioma": "IOMA",
    "swiss medical": "Swiss Medical",
    "s medical": "Swiss Medical",
    "s medicsal": "Swiss Medical",
    "sancor": "Sancor Salud",
    "sancor 1000": "Sancor 1000",
    "sancor 3000": "Sancor 3000",
    "sancor 4000": "Sancor 4000",
    "sancor 4500": "Sancor 4500",
    "apsot": "Apsot",
    "cima": "Cima",
    "medife plata": "Medife Plata",
    "smata": "Smata",
    "suteba": "Suteba",
    "udocba": "Udocba",
    "uocra": "Uocra",
    "utedyc": "Utedyc",
}


def backfill(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ObraSocial = apps.get_model("customers", "ObraSocial")
    Receta = apps.get_model("prescriptions", "Receta")
    catalogo = {os.nombre.lower(): os for os in ObraSocial.objects.using(db_alias).all()}

    def resolver(nombre_canonico):
        obj = catalogo.get(nombre_canonico.lower())
        if obj is None:
            obj = ObraSocial.objects.using(db_alias).create(nombre=nombre_canonico)
            catalogo[nombre_canonico.lower()] = obj
        return obj

    for receta in Receta.objects.using(db_alias).exclude(obra_social="").iterator():
        clave = " ".join(receta.obra_social.split()).lower()
        nombre_canonico = MAPEO.get(clave)
        if nombre_canonico is None:
            continue  # valor no mapeado: se deja sin obra social, revisar a mano
        receta.obra_social_fk = resolver(nombre_canonico)
        receta.save(update_fields=["obra_social_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0014_receta_obra_social_fk'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
