# Generated by Django 6.0.6 on 2026-07-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0015_backfill_obra_social'),
    ]

    operations = [
        migrations.RemoveField(model_name='receta', name='obra_social'),
        migrations.RenameField(model_name='receta', old_name='obra_social_fk', new_name='obra_social'),
    ]
