# Generated by Django 6.0.6 on 2026-07-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0016_rename_obra_social_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['-creado'], 'verbose_name_plural': 'recetas'},
        ),
        migrations.AddField(
            model_name='receta',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, help_text="Cuándo se cargó o corrigió por última vez (para poder ordenar por 'última modificación')."),
        ),
    ]
