"""
Django settings for stockero project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'customers',
    'prescriptions',
    'sales',
    'contact_lenses',
    'notificaciones',
    'core',
    'tenants',
]

DATABASE_ROUTERS = ['tenants.db_router.TenantRouter']

# --- Email ---
# Estas variables estaban en el .env pero settings no las leía, así que el
# email nunca se enviaba. Con esto queda funcional (para backups y avisos).
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'no-reply@optica.local')

# A qué casilla se manda el backup diario de la base (comando backup_db).
BACKUP_EMAIL = config('BACKUP_EMAIL', default='')

# Papelera: cuántos días queda algo borrado (recuperable) antes de que la purga
# programada (comando vaciar_papelera) lo elimine definitivamente.
PAPELERA_DIAS_RETENCION = config('PAPELERA_DIAS_RETENCION', default=7, cast=int)


# --- Notificaciones push (Web Push) ---
# Si no hay claves cargadas, el push queda simplemente desactivado y la app
# funciona igual. Para generarlas: python manage.py generar_vapid_keys
VAPID_PUBLIC_KEY = config('VAPID_PUBLIC_KEY', default='')
VAPID_PRIVATE_KEY = config('VAPID_PRIVATE_KEY', default='')
VAPID_CONTACTO = config('VAPID_CONTACTO', default='soporte@optica.local')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'tenants.middleware.TenantMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenants.middleware.AdminTenantSwitchMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stockero.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stockero.context_processors.rol_usuario',
                'stockero.context_processors.configuracion',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockero.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if config('DATABASE_URL', default=''):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=config('DATABASE_URL'), conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Red de seguridad: si falta un archivo en el manifest (ej: un asset nuevo sin
# collectstatic), WhiteNoise devuelve el nombre sin hashear en vez de tirar un
# 500 que voltea TODA la página. El fix de fondo es que collectstatic corra en
# el deploy (ver Procfile).
WHITENOISE_MANIFEST_STRICT = False

# En los tests no se corre collectstatic, así que el storage con manifest
# (hash de archivos) falla al buscar 'img/logo.png' y demás. Usamos el storage
# simple cuando estamos corriendo la suite de tests.
import sys
if 'test' in sys.argv:
    STORAGES["staticfiles"]["BACKEND"] = "django.contrib.staticfiles.storage.StaticFilesStorage"

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# El default de Django (1000) se queda corto para la tabla de revisión del
# importador de listas de precios (varios inputs por fila, y una lista de
# proveedor puede traer miles de productos).
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Ojo: durante los tests (aunque DEBUG=False, como en CI) NO se aplica el
# hardening HTTPS. Si no, SECURE_SSL_REDIRECT redirige cada request HTTP del
# test client con un 301 antes de llegar a la vista, y toda la suite falla.
if not DEBUG and 'test' not in sys.argv:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# --- Logging ---
# Sin esto, los logger.info de la app (ej: bajas de suscripción push, avisos
# que no salieron) no aparecen en los logs de Railway y quedan ciegos. Se
# manda todo a consola, que es lo que Railway captura. El nivel se puede
# subir/bajar por variable de entorno sin tocar código.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "{asctime} {levelname} {name}: {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        # Apps propias: se ve el detalle (INFO) de push, avisos, etc.
        app: {"handlers": ["console"], "level": config("LOG_LEVEL", default="INFO"), "propagate": False}
        for app in ["notificaciones", "contact_lenses", "sales", "inventory", "prescriptions", "customers"]
    },
}

# Durante los tests hay varios que prueban a propósito caminos de error (el
# push que se cae, CSRF rechazado, etc.). Esos logueos son ESPERADOS, pero
# ensucian la salida con tracebacks/WARNINGs y dan la falsa impresión de que
# los tests fallan. Se silencia todo el logging mientras corre la suite.
if 'test' in sys.argv:
    import logging
    logging.disable(logging.CRITICAL)
