# Generated by Django 5.2.15 on 2026-07-05 15:14

import django.core.validators
from django.db import migrations, models


def separar_nombre_apellido(apps, schema_editor):
    """El nombre completo venía en un solo campo (ej: 'Ana Rodríguez'). Se
    parte por el primer espacio: la primera palabra queda en 'nombre' y el
    resto (si hay) en 'apellido'. Es una heurística razonable para nombres a
    la española, no perfecta (ej: nombres compuestos) — se puede corregir a
    mano en los pocos casos que hagan falta."""
    Cliente = apps.get_model("customers", "Cliente")
    for cliente in Cliente.objects.using(schema_editor.connection.alias).exclude(nombre=""):
        partes = cliente.nombre.split(" ", 1)
        if len(partes) == 2:
            cliente.nombre, cliente.apellido = partes[0], partes[1]
            cliente.save(update_fields=["nombre", "apellido"])


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(separar_nombre_apellido, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d*$', 'Ingresá solo números.')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^\\d*$', 'Ingresá solo números.')]),
        ),
    ]
