# Generated by Django 6.0.6 on 2026-07-24 22:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_fusionar_obras_sociales_duplicadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='obrasocial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='obrasocial_nombre_ci_unique'),
        ),
    ]
