# Generated by Django 5.2.15 on 2026-07-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_promocion'),
        ('sales', '0002_vendedor_venta_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_items', to='inventory.promocion'),
        ),
    ]
