# Generated by Django 5.2.15 on 2026-07-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuotas',
            field=models.PositiveIntegerField(blank=True, help_text='Solo aplica si la forma de pago es tarjeta.', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('TRA', 'Transferencia'), ('QR', 'QR')], max_length=3),
        ),
    ]
