# Generated by Django 5.2.15 on 2026-07-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_receta_vendedor'),
        ('sales', '0005_venta_cuotas_venta_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='receta_sugerida',
            field=models.ForeignKey(blank=True, help_text='Receta que el vendedor eligió asociar a esta venta al elegir el cliente: los items que requieran receta la usan de default (se puede cambiar por item igual).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='prescriptions.receta'),
        ),
    ]
