# Generated by Django 5.2.15 on 2026-07-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_venta_receta_sugerida'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='incidencias_detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tiene_incidencias',
            field=models.BooleanField(default=False, help_text='Se marca sola si durante la venta hubo que forzar stock insuficiente o se escaneó un código que no existía, para poder revisarlo después.'),
        ),
    ]
