# Generated by Django 5.2.15 on 2026-07-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_venta_incidencias_detalle_venta_tiene_incidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='entregado',
            field=models.BooleanField(default=True, help_text='Destildar si el cliente todavía no se llevó el pedido (ej: reserva/encargo a retirar después). Se puede completar el pago y marcar la entrega más adelante.'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuánto pagó el cliente hasta ahora (puede ser menor al total si dejó una seña).', max_digits=10),
        ),
    ]
