# Generated by Django 5.2.15 on 2026-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_venta_entregado_venta_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuotas_saldo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_manual_tipo',
            field=models.CharField(blank=True, choices=[('PCT', 'Porcentaje'), ('FIJ', 'Monto fijo')], max_length=3),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_manual_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago_saldo',
            field=models.CharField(blank=True, choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('TRA', 'Transferencia'), ('QR', 'QR')], help_text='Forma de pago con la que se canceló el saldo (puede ser distinta a la de la seña).', max_length=3),
        ),
    ]
