# Generated by Django 5.2.15 on 2026-07-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_venta_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='notificado',
            field=models.BooleanField(default=False, help_text='Se avisó al cliente (ej: por WhatsApp) que su pedido está listo para retirar.'),
        ),
    ]
