# Generated by Django 5.2.15 on 2026-07-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_venta_notificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='armazon_de_cliente',
            field=models.BooleanField(default=False, help_text='El cliente trajo su propio armazón: no se vendió ninguno en esta venta.'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='armazon_venta_item',
            field=models.ForeignKey(blank=True, help_text='Item de esta misma venta que es el armazón donde se monta este cristal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cristales_asociados', to='sales.ventaitem'),
        ),
    ]
