# Generated by Django 6.0.6 on 2026-07-21 01:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_ventaitem_armazon_de_cliente_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='vendedor_nombre_unico_ci'),
        ),
    ]
