# Generated by Django 6.0.6 on 2026-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_ventaitem_armazon_de_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_obra_social',
            field=models.BooleanField(default=False, help_text="La venta se gestiona por obra social: puede que el cliente no pague nada en el momento. Queda en 'Ventas por obra social' para revisar y terminar a mano."),
        ),
        migrations.AddField(
            model_name='venta',
            name='obra_social_resuelta',
            field=models.BooleanField(default=False, help_text='Se marca a mano cuando ya se terminó de gestionar la venta con la obra social (ej: se cobró o se descartó el trámite).'),
        ),
    ]
