# Generated by Django 6.0.6 on 2026-07-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_vendedor_vendedor_nombre_unico_ci'),
        ('sales', '0015_venta_obra_social'),
    ]

    operations = [
    ]
