# Generated by Django 6.0.6 on 2026-07-21 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_obra_social'),
        ('sales', '0016_merge_20260720_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='obra_social',
            field=models.ForeignKey(blank=True, help_text='Qué obra social se usa en esta venta (si es_obra_social).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='customers.obrasocial'),
        ),
    ]
