# Generated by Django 6.0.6 on 2026-07-23 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_venta_obra_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario con el que esta persona entra al sistema. Sirve para mandarle avisos al celular (ej: cuando le agendan una prueba de lentes de contacto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to=settings.AUTH_USER_MODEL),
        ),
    ]
