# Generated by Django 6.0.6 on 2026-07-24 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_sembrar_obras_sociales'),
        ('prescriptions', '0009_receta_es_lentes_contacto_and_more'),
        ('sales', '0018_vendedor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha'], name='venta_estado_fecha_idx'),
        ),
    ]
