# Generated by Django 6.0.6 on 2026-07-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_venta_venta_estado_fecha_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
