# Generated by Django 6.0.6 on 2026-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_venta_eliminado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas a mano del vendedor/a sobre esta venta puntual (ej: algo que pasó durante la atención), para que quede registrado junto a la venta.'),
        ),
    ]
