# Generated by Django 6.0.6 on 2026-09-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_venta_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='obra_social_cobertura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='obra_social_tipo',
            field=models.CharField(blank=True, choices=[('REI', 'Reintegro de obra social, cliente paga total'), ('PAR', 'Obra social cubre parte de la compra'), ('COM', 'Obra social cubre el anteojo completo')], help_text='Cómo interviene la obra social en esta venta (solo si es_obra_social).', max_length=3),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='cubierto_obra_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='es_obra_social',
            field=models.BooleanField(default=False, help_text="La venta se gestiona por obra social: puede que el cliente no pague nada en el momento. Una vez cobrada y entregada, queda en 'Ventas por resolver con OS'."),
        ),
        migrations.AlterField(
            model_name='venta',
            name='obra_social_resuelta',
            field=models.BooleanField(default=False, help_text='Se marca a mano cuando ya se terminó de cerrar el trámite administrativo con la obra social (ej: se facturó o se descartó).'),
        ),
    ]
