# Generated by Django 6.0.6 on 2026-09-05 22:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_venta_obra_social_cobertura_venta_obra_social_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('fondo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totales_por_forma_pago', models.JSONField(blank=True, default=dict)),
                ('total_devoluciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EgresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(help_text='Ej: pago a proveedor, vuelto, retiro del dueño.', max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
